### ISSUE TITLE
Android permissions?

### ISSUE THREAD

**Issue by jeffallen** [UNTILabs/1point5#1]
Hello. I got interested in this app because Vice says it doesn't work:
  https://www.vice.com/en_us/article/g5xz37/united-nations-coronavirus-app-1point5-doesnt-work

I noticed that it probably uses the wrong location permission:
```
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
```
See https://github.com/randdusing/cordova-plugin-bluetoothle/issues/579

In general, the app should be more clear about the limitations of BlueTooth LE, that vendors do not allow apps to scan in the background, that your app does not seem to have a background service that continues running when the app is not in the foreground, etc.

This is an ok idea, but getting a reputation fo "doesn't even work" is not going to be helpful to the app's launch.

**Comment by re2005** [comment]
Hi @jeffallen thanks for reaching out.

The ACCESS_FINE_LOCATION is when you need GPS data?  In our case it's not necessary, I believe that people having issues is because their BLE may be limited.

The APP will work on background (Android only) but only for `APP to APP` detection, so we can set a service ID and scan only for that id.

iOS 13.5 beta also allows background scanning, let's wait for that.

I think it's a great start having VICE to talk about that, and now people (like you) will come to help us and contribute. This is a social thing we are all part and responsible.

Cheers

**Comment by jeffallen** [comment]
"In order to use Bluetooth features in your application, you must declare two permissions. The first of these is BLUETOOTH. You need this permission to perform any Bluetooth communication, such as requesting a connection, accepting a connection, and transferring data.
The other permission that you must declare is ACCESS_FINE_LOCATION..."

https://developer.android.com/guide/topics/connectivity/bluetooth#Permissions

**Comment by re2005** [comment]
As far we tested with multiple android devices this was never an issue.
But to be sure it won't be because of this permission I've added.

https://github.com/UNTILabs/1point5/pull/2

Feel free to create PR's if you spot anything else that we're missing.

Thanks @jeffallen

**Comment by swbradsh** [comment]
> The other permission that you must declare is ACCESS_FINE_LOCATION..."
> 
> https://developer.android.com/guide/topics/connectivity/bluetooth#Permissions

If you read futher down, you should have saw this part:

> Note: If your app targets Android 9 (API level 28) or lower, you can declare the ACCESS_COARSE_LOCATION permission instead of the ACCESS_FINE_LOCATION permission.

Apache Cordova doesn't support API 29 yet, so this app is fine with ACCESS_COURSE_LOCATION.
